[package]
name = "ibapi-integration-sync"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
ibapi = { path = "../..", default-features = false, features = ["sync"] }
ibapi-test = { path = "../common" }
anyhow = "1"
env_logger = "0.11"
serial_test = "3.1.1"
time = "0.3"
